version: "3"

services:

  nginx:
    build:
      context: nginx
    image: henriquelucasdf/nginx_node:latest
    container_name: nginx_node
    restart: always
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
      - node_app

  node_app:
    build:
      context: node
    image: henriquelucasdf/node_fc:prod
    entrypoint: dockerize -wait tcp://db:3306 -timeout 60s docker-entrypoint.sh
    command: node index.js
    container_name: node
    restart: unless-stopped
    networks:
      - nodenet
    volumes:
      - ./node/src/:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7.16 # problema de permissão do wsl2 com o mysql:5.7
    command:
      - --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

networks:
  nodenet:
    driver: bridge
